---
name: Go CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run linters
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Cache test data
        uses: actions/cache@v4
        with:
          path: tests/data
          key: tests-data-${{ hashFiles('scripts/download-dumps.sh') }}

      - name: Download test data
        if: steps.cache.outputs.cache-hit != 'true'
        run: scripts/download-dumps.sh

      - name: Run tests
        run: go test
