---
name: Go CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Run linters
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Install dependencies
        run: go mod tidy

      - name: Cache test data
        uses: actions/cache@v4
        with:
          path: tests/data
          key: tests-data-${{ hashFiles('scripts/download-dumps.sh') }}

      - name: Download test data
        if: steps.cache.outputs.cache-hit != 'true'
        run: scripts/download-dumps.sh

      - name: Run tests
        run: go test
